### ISSUE TITLE
Adding target="_blank" to referrers

### ISSUE THREAD

**Issue by flowdee** [ibericode/koko-analytics#111]
I assume the title speaks for itself 😄 

Maybe adding "nofollow" would make sense as well?

**Comment by dannyvankooten** [comment]
On the dashboard page? What would adding rel=nofollow accomplish? That is really just for crawlers not to follow that link, right? 

Personally I am no fan of adding target=blank because it forces the user to open in a new tab without being able to override our choice, whereas now the choice is theirs: Ctrl+Click for a new tab, Click for current tab.

**Comment by flowdee** [comment]
Ok!
