### ISSUE TITLE
Feature suggestion: Count device types

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/koko-analytics#12]
For each new site visitor, keep track of their device type so we can show a simple device split in the totals bar at the top of the dashboard page.

Personally I think a "mobile" and "desktop" split is good enough, but I'd love to get some input on this from others. 

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by Zodiac1978** [comment]
If the WordPress function `wp_is_mobile` is not sufficient there is a plugin called mobble which is using this PHP library which could be used for more detailed info: http://mobiledetect.net/

**Comment by askel45** [comment]
I think also include 'tablets'.

**Comment by marcelismus** [comment]
+1

**Comment by BiancaNL** [comment]
+1. If it's not much of a hassle include tablets as well. This information is really handy for UI/UX/ content optimization. For some users mobile and desktop indication will be sufficient but for others tablet as well. Kind of depends on the type of website/ app thats being designed I think.

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/extra-visitor-data/

**Comment by binaryfire** [comment]
+1

I'm not sure how Koko works exactly, but I'm assuming it's using JavaScript for tracking? Because if it was using PHP, no visits to cached pages or pages served by CDNs like Cloudflare would be recorded.

So the user agent detection would need to happen via JS, right? Which would be the lightest way of doing it anyway

**Comment by cbirdsong** [comment]
A “tablet” device category is not really useful nowadays. Apple changed the iPad’s user agent to be the same as Mac Safari a couple versions ago in order to avoid mobile-optimized sites being served to laptop-sized screens. A “tablet” category that excludes iPads as “tablet” does not seem super useful to users.

**Comment by dannyvankooten** [comment]
We're moving feature ideas to GitHub discussions. Vote tracking for this feature has moved here: #219
