### ISSUE TITLE
Zero Visitors but some pageviews

### ISSUE THREAD

**Issue by Zeit08** [ibericode/koko-analytics#127]
I am unsure of how to interpret this data. The screen below shows 0 visitors, but still some pageviews. How is that possible?

C**ould someone explain me** with different words h**ow the visitors and pageviews are getting counted?** I read the FAQ on the wordpress.org page, but still it is not clear to me.

![image](https://user-images.githubusercontent.com/45097367/130668554-2548c043-9481-4a58-bfa4-b52c07959c1f.png)

 I also saw once _1 visitor and 77 pageview_, which does let me think that a single visitor has seen 77 pages (included reloading of those pages).  But it may be not trued as the  above phenomena happened

**Comment by dannyvankooten** [comment]
Hello,

This may happen because of cookie lifetimes, eg. the user landed on your website close to midnight, viewed a bunch of pages and then after midnight they kept on viewing some more pages.

1 visitor which added pageviews to two dates.

We've improved upon this in d1e4e209c19d50456e08c843d96aa741873b4d13 to clear up some of the confusion.
