### ISSUE TITLE
Feature Suggestion: A Standalone, Non-WordPress Version

### ISSUE THREAD

**Issue by bhadaway** [ibericode/koko-analytics#159]
I'm officially done with Google Analytics and I'm never going back. Koko solves my needs for WP, but what about a simple, static website?

How easy would it be to port the plugin over as standalone PHP/MySQL script for a plain ol' website on LAMP?

---

_Please vote on this feature suggestion using :+1: or :-1: below._

**Comment by dannyvankooten** [comment]
Hey @bhadaway,

This is a great idea and obviously one I've mulled over at times. It actually existed in the form of (the original version of) [Fathom](https://github.com/usefathom/fathom) already, which I built before deciding piggybacking along on WordPress would allow me to reach a much broader audience.

The issue was that because of it being self-hosted, the audience was pretty much limited to developers and devops people. Perhaps this would be alleviated a little bit if it were built in PHP instead of Go? 

As it stands the plugin is pretty tightly coupled to WordPress so it would be some effort. The dashboard itself is written in React and just fed some initialization data from WordPress so can pretty much be ported as is, but the tracking snippet and storage of data is another story I'm afraid. 

Another issue is that the plugin currently uses post/page ID's internally to a) save on a ton of storage space and b) know about the canonical version of each page. With a standalone version this should be designed differently, which is actually harder than one might think at first.

**Comment by dannyvankooten** [comment]
Whoops, sorry. Did not mean to close this as I'm definitely still keen on this... It would just be such a massive time investment that I do not see it happening any time soon.

**Comment by bhadaway** [comment]
Oh yeah, I realize that if it happens at all, it won't be for a while. Plus, it's not something you'd necessarily have to do alone. I think Koko is special (I may write up a more thorough review on one of my blogs) and that the audience will grow. Along with popularity will hopefully come people that are willing to help extend the project.

**Comment by ddxv** [comment]
Not sure if this is the same as the above suggestion, but I have a personal wordpress that sits at myblog.com and then my own managed sites at foo.myblog.com  is there anyway I can trigger callbacks to those pages despite that they are not Wordpress? Again, there is an existing wordpress + koko installation (even on the same machine) so not sure if that makes this more likely than a fully independent koko site.

**Comment by dannyvankooten** [comment]
Hello everyone. I'm just closing this as we're going to keep the issue tracker for issues/bugs only and track feature suggestions using [GitHub discussions here](https://github.com/ibericode/koko-analytics/discussions/categories/ideas). That way we can better prioritize what features to work on next.

**Comment by dannyvankooten** [comment]
There's been some progress on this, code-named [Teller](https://teller.dvk.co/). It started out as a PHP installation but without WordPress it wouldn't be as easy to host as I hoped (because it needs a cronjob) so it's now built on Golang instead. This way I can share standalone binary applications that you can drop and run from your Windows or Linux based server and then it immediately works.

Once you have it running somewhere you can drop a tracking snippet on any website, point it to your Teller application and it starts tracking pageviews:

![image](https://github.com/ibericode/koko-analytics/assets/885856/54473eb0-7740-4d0d-98cd-d02e8c47ea73)

**Comment by bhadaway** [comment]
Was the "Teller" project shelved?
