### ISSUE TITLE
Not displaying Title/Link for WP Events Manager post-type

### ISSUE THREAD

**Issue by davinian** [ibericode/koko-analytics#18]
Hi, I am testing on one of my websites alongside Google Analytics Dashboard for WP (GADWP) and everything seems to work great apart from one thing!

It counts views but fails to display the Title/Link of WP Events Manager (https://wp-events-plugin.com/) posts (see attached).

Let me know if you need me to run any tests or require additional info.

David

![koko-analytics](https://user-images.githubusercontent.com/1258121/69007422-7c353580-0935-11ea-847a-8506d2b93e56.png)

**Comment by dannyvankooten** [comment]
Hey @davinian,

This was a nice catch and taught me something about WP's internal. Apparently when querying posts and using `post_type=any`, it really means `any-except-those-excluded-from-search`.

Fixed it now by explicitly passing array of all post types so that those from Events Manager are also included.

**Comment by davinian** [comment]
Thanks @dannyvankooten I'll update / test and let you know results 👍
