### ISSUE TITLE
Check pageviews path when checking endpoint

### ISSUE THREAD

**Issue by arnelap** [ibericode/koko-analytics#184]
When you move to another host, the absolute path of the pageviews file changes and the koko-analytics-collect.php endpoint file needs to be re-created /update with the new path. 

This is something that could be part of the endpoint check, by checking if the pageviews.php file is writable and if not, try to update the path and try again.

**Comment by dannyvankooten** [comment]
Whether the buffer file is writable is already checked by simply sending a dummy request to the custom endpoint, but that would still return a `200 OK` response if the OLD buffer filepath was still writable too.

4acaad8306247c770048f1c3466a0955895e3d8f now checks to see if the current buffer file is actually in the custom endpoint file and otherwise re-installs it with the correct current path.
