### ISSUE TITLE
Cron Job Hammering Stylesheet

### ISSUE THREAD

**Issue by dubsarGimillu** [ibericode/koko-analytics#190]
On a Wordpress site with the Ekiline theme, the second biggest consumption of bandwidth in 2023 was a Wordpress Con job hitting /wp-content/themes/ekiline/assets/css/style-atf.css (about 200 hits per day from the IP address of the server).  When the hosting provider switched the Wordpress Cron job with a regular Unix Cron job, the traffic seemed to reduce, but I did get a warning in wp-admin: "There seems to be an issue with your site's WP Cron configuration that prevents Koko Analytics from automatically processing your statistics. If you're not sure what this is about, please ask your webhost to look into this."

I also see a warning under wp-admin > Site Health: "The scheduled event, koko_analytics_aggregate_stats, is late to run"

This issue has many moving parts and I can't guarantee that I have located the cause in a koko analytics - theme interaction.  Have there been any other cases where Koko Analytics hit part of the site theme again and again like this?

**Comment by dannyvankooten** [comment]
The warning message you're seeing does not mean that it was Koko Analytics requesting the URL of your stylesheet. There shouldn't be anything in the plugin that causes it to do so.

That message does however mean that the `koko_analytics_aggregate_stats` event is not being fired on time, which could be due to your WP Cron system no longer working. I would see to ensure that the regular unix cron job is set up correctly.
