### ISSUE TITLE
Still not functioning correctly

### ISSUE THREAD

**Issue by paaljoachim** [ibericode/koko-analytics#235]
Hi

I kind of gave up on Koko Analytics. But I like it so much that I am doing a last effort here.
I did post on the WP org support forum. https://wordpress.org/support/topic/showing-only-two-stats-in-october/
I am following up here on Github because it is easier to share screenshots of what I see.

![Screenshot 2023-12-12 at 15 44 19](https://github.com/ibericode/koko-analytics/assets/5323259/f2042fb2-d7fe-48d2-9a1d-788041ca37e3)

I do not know how to get Koko Analytics to work.
I have turned off the Brave shield - No difference.
A client mentioned for me as he logged in that stats looked strange. He is using another browser.

I really want it to work again, as I use the plugin on a lot of sites. I would like to also create a tutorial for my WP tutorial site here:
https://easywebdesigntutorials.com/

Thanks!

**Comment by dannyvankooten** [comment]
Hello @paaljoachim,

It's not the tracking that isn't working but the background aggregation process. This means that your WP Cron schedule isn't working as expected, which is usually due to some other process blocking the WP Cron thread by having a scheduled task in there that never finishes. Any scheduled task due after this broken task (like the one Koko Analytics uses for aggregating statistics) will not run until this task is cleared from your scheduled events list.

We also run this aggregation process whenever you visit the analytics page in your WordPress admin to ensure you're viewing the latest data. This is why you're only seeing statistics on the days you actually visit your dashboard.

You can install a plugin like Advanced Cron Manager to debug which scheduled event is at the top of the list that never finishes.

**Comment by paaljoachim** [comment]
Hey @dannyvankooten Danny

Thank you for the response!
I went ahead and installed and activated Advanced Cron Manager.
Went to Tools -> Cron Manager.
I am not seeing anything that is stuck in the top.

This is what I see:

![Cron Manager screen](https://github.com/ibericode/koko-analytics/assets/5323259/b62b66ac-0d98-4341-8aa3-b8331e825e28)

**Comment by dewolkenwagen** [comment]
For now let's treat this as a support question and deal with it on the wordpress forum.
We reserve git for confirmed bugs only.

**Comment by dannyvankooten** [comment]
@paaljoachim Can you search for `koko_analytics_aggregate_stats` in the list of events? It should be scheduled to run every minute.

**Comment by paaljoachim** [comment]
I took a full size screenshot.

![easywebdesigntutorials com_wp-admin_tools php_page=advanced-cron-manager](https://github.com/ibericode/koko-analytics/assets/5323259/63a2ef0d-871f-4022-8a9f-0e091d413c88)

koko_analytics_aggregate_stats is not showing up.

**Comment by paaljoachim** [comment]
Searching only for koko_analytics

![Screenshot 2023-12-13 at 12 52 20](https://github.com/ibericode/koko-analytics/assets/5323259/baa104a6-d7be-4439-8b5c-2b379913f2ec)

**Comment by paaljoachim** [comment]
Hey @dannyvankooten 

I got the bugs shaken off. Deactivating Duplicator Pro. Doing a bunch of hard refreshes brought the daily stats back again working as it should. I am in contact with Duplicator support to get this thing fixed.

Thanks for being there! Buzz me when a good time would be for me to create a tutorial showing off Koko Analytics. Thanks.
