### ISSUE TITLE
Problems with WP Cron acting up

### ISSUE THREAD

**Issue by paaljoachim** [ibericode/koko-analytics#245]
Hey

I am adding the issue here as I am able to easier add screenshots.
**Current issue is at wp.org support for the plugin: https://wordpress.org/support/topic/problems-with-wp-cron-acting-up/**

NB. We can and probably should continue the thread directly on wp.org support to make it more visible for others.
But as I said I would like to add a screenshot and it is better to have it available.

![Screenshot 2024-06-13 at 13 32 09](https://github.com/ibericode/koko-analytics/assets/5323259/299c21ad-928f-4a37-830c-75f9e48a5910)

**Comment by dannyvankooten** [comment]
Hello @paaljoachim,

Some other scheduled event is blocking your queue; most likely because it is running into a fatal error. It is probably the item at the top of the queue, "nf_marketing_feed_cron". 

I would check your PHP error log and then ask the plugin developer of the plugin that event is coming from to fix the issue (if needed).
