### ISSUE TITLE
Adblocker blocking script

### ISSUE THREAD

**Issue by onetrev** [ibericode/koko-analytics#248]
I noticed my ad blocker (uBlock Origin) blocks the Koko Analytics script. I'm assuming other ad blockers would do the same. 

As such, this obviously means Kobo Analytics is not recording visitor counts from anyone else with an ad blocker. The script that Plausible Analytics uses seems to avoid ad blockers, so I wondered if there was a reason why the Kobo Analytics one is being blocked?

**Comment by dannyvankooten** [comment]
Hello @onetrev,

I can't talk for Plausible but Koko Analytics is on the EasyList privacy list, which is an open-source community maintained list. Most likely it has been added by someone not knowing that Koko Analytics really only does aggregate counts and does not track anything visitor specific, yet it operates under the philosophy that it doesn't hurt to just block it either (zero trust).

From a quick Google search I do think Plausible is also on that EasyPrivacy list, except if you're using a self-hosted install? See [here](https://github.com/plausible/analytics/issues/158) and [here](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L1691).

We could petition the list authors but I have very little hopes for Koko to be whitelisted since the counting is still not anything that benefits the visitor, despite it absolutely being privacy friendly.

**Comment by dannyvankooten** [comment]
Here's Plausible answering pretty much the same question, with some interesting looking possible workarounds: https://plausible.io/docs/proxy/introduction

I have thought about implementing a workaround in Koko Analytics as well, but it quickly becomes a cat-and-mouse game between filter list authors and the plugin, so have simply accepted that stats will exclude people running an ad-blocker.

**Comment by onetrev** [comment]
Hey @dannyvankooten, thank you so much for looking into this. Very good of you. Sorry I didn't realise things were the same with Plausible. My previous experience with them was for a large client and I forgot we used the proxy workaround.

I guess one positive is you now have more info should you get this question a few more times and need to add it to your FAQs. 😏
