### ISSUE TITLE
Correct use of <noscript>?

### ISSUE THREAD

**Issue by edent** [ibericode/koko-analytics#250]
I am using the Cookie for tracking. I also have a caching plugin.  I have excluded `/koko-analytics-collect.php` from the cache.

This is the code I'm using in the footer of every page:

```php
<noscript>
	<img src="/koko-analytics-collect.php?nv=0&up=0&p=<?php echo get_queried_object_id(); ?>" 
	alt="" width="0" height="0" class="hidden">
</noscript>
```

Does that look right to you? Thanks!

**Comment by dannyvankooten** [comment]
@edent Looks pretty good to me, but two things I'd like to bring to your attention:


### Wrap in `is_singular()` 

I would maybe throw a bit more PHP logic in there because of a limitation that Koko Analytics currently only tracks posts, pages and custom post types. So something like this:

```html
<?php if (is_singular()) { ?>
<noscript>
	<img src="/koko-analytics-collect.php?nv=0&up=0&p=<?php echo get_queried_object_id(); ?>" 
	alt="" width="0" height="0" class="hidden">
</noscript>
<?php } // end if is singular ?>
```

I am also not sure what `get_queried_object_id()` returns on taxonomy archives, so the above will also prevent this from sending a request with `p=0` which will increment the counter for the homepage (erroneously, in this case).

### Does the response for that `<img>` work correctly?

Previously the endpoint returned a 1x1 px transparent GIF, but this is no longer the case. Let me know in case you spot any issues with the endpoint returning an empty response body or a non-image `Content-Type` header. In that case we would need to modify the endpoint to dynamically return a different response from the `<img>` initiated request vs. the JS initiated request (which we can easily do by checking for `GET` vs `POST` requests).
