### ISSUE TITLE
Font size consistency

### ISSUE THREAD

**Issue by jan-vandenberg** [ibericode/koko-analytics#266]
I don't know if it is intentional, but the fact that these are not the same size stands out ;)

![image](https://github.com/user-attachments/assets/682e3f38-b0b9-4d4b-94bf-8d56bdfb4305)

**Comment by ocean90** [comment]
Looks intentional, the first is a paragraph, the second is a heading.

**Comment by dannyvankooten** [comment]
This is indeed intentional and uses the default CSS styles for `<h3>` and `<p>` elements inside the WordPress admin. I agree it can look a little off, but it does match the styling of the rest of the page in my opinion.

We could make headings inside our dashboard widget bold, but that would deviate from the default WP admin styles so I am not sure. Thoughts?

https://github.com/ibericode/koko-analytics/blob/e5a5f6be4370f31ee7b74be915cd189b40e7f274/src/views/dashboard-widget.php#L22-L24

https://github.com/ibericode/koko-analytics/blob/e5a5f6be4370f31ee7b74be915cd189b40e7f274/src/views/dashboard-widget.php#L28-L30

**Comment by jan-vandenberg** [comment]
Ah that explains it! I have no particular opinion other than that it looks off.

But thinking about it: the second text might even not be necessary because it is implicit.

Less is more.
