### ISSUE TITLE
Database error when installing

### ISSUE THREAD

**Issue by sdegetaus** [ibericode/koko-analytics#4]
![image](https://user-images.githubusercontent.com/30123984/68724719-e2ab0400-0581-11ea-8a30-6c016f890239.png)

At first, I thought I was making a mistake when installing the project via the command line, but it is happening also from the WordPress official repo.

It has happened in my live website and also in my local environment.

Inside phpMyAdmin, the table `koko_analytics_referrer_urls` was missing (as well as the wp-option `koko_analytics_settings`). Naturally, the plugin admin area didn't show anything!

To fix it, I created the table `koko_analytics_referrer_urls` by myself, and that fixed the issue.

I found this explanation on [StackOverflow](https://stackoverflow.com/questions/3489041/mysqlerror-specified-key-was-too-long-max-key-length-is-1000-bytes), but I am not sure exactly how to fix it.

Perhaps an important note: I am using a custom table prefix.

Let me know if you need more info 🙂.

**Comment by sdegetaus** [comment]
I just did a couple of tests, and two things worked for me (separately):

- setting VARCHAR to 100, or...
- changing the UNIQUE INDEX to `id` instead of `url`

**Comment by dannyvankooten** [comment]
Hey @sdegetaus,

Nice catch!

The issue is that Koko was using `utf8mb4` as its charset for storing textual columns like `VARCHAR` which comes with support for emoji's, while taking up 4 bytes per character. This causes issues with the `UNIQUE INDEX` on the `url` column as the total size of that column exceeds the 767 bytes which are allowed in your version of MySQL.

In a27d9c7634ef5305498a8b4fe13ef2bd899bb7bb I've switched the charset for all Koko Analytics' tables to [ASCII](https://ascii.cl/) which is more than enough for storing date strings and URL's, as it matches the [official spec for URI's](https://www.w3.org/Addressing/URL/url-spec.html). It also uses just a single byte per character, so we can potentially increase our character limit on the URL column to `767` if necessary.

**Comment by sdegetaus** [comment]
Tested it in my local server, and it worked like a charm. Thanks!
