### ISSUE TITLE
Tooltips on edges of a chart cause horizontal scrollbar to appear

### ISSUE THREAD

**Issue by ndegruchy** [ibericode/koko-analytics#65]
When viewing charts for different days, if the bar graph has an item at the end, the mouseover tooltip causes a horizontal scroll. As pictured:

![Screenshot_20200505_100327](https://user-images.githubusercontent.com/52262673/81075169-ff345300-8eb7-11ea-965a-3b1352d98129.png)

While not a major issue, it is kind of annoying. Perhaps a `overflow-x: none` or somehow push the tooltip within the frame.

**Comment by dannyvankooten** [comment]
Hey @ndegruchy,

Nice find! 

However: after spending some time on this it proved to be quite hard to fix without breaking other things, so I am choosing not to spend any more time on this. For now...

**Comment by ndegruchy** [comment]
Fair enough. The only way I could think of to fix it is either set the horizontal overflow to hidden, or to somehow modify the tooltip to detect viewport edges and switch to a different 'side'.

Thanks for the effort on the project, anyway!

**Comment by jayhybrid** [comment]
Hey,

I consider myself good with CSS and I have 2 ideas how to make this work. One I was able to successfully test, for the other I need more info for. The second approach is also my preferred because it seems cleaner to me.

1. Make HTML `body` `overflow-x: hidden;`
2. Move `.chart-tooltip` into `#koko-analytics-admin` and make it `overflow-x: hidden;`

Solution 2 did not work for me, and I'm guessing due to some JS selector, could this be easily changed? I'd be willing to make a PR if you can give me some guidance on this.

**Comment by jayhybrid** [comment]
Alright, @ndegruchy I totally can understand you know. It seems like a rabbit hole for me. I will make a PR for solution 1.
