### ISSUE TITLE
Feature: enhance most read posts widget with featured image and styling like most recent widget does

### ISSUE THREAD

**Issue by jeroenrotty** [ibericode/koko-analytics#74]
It would be very cool to be able to style the Koko widget the same as the most recent widget does, with featured image on the left and date just under the title on the right.

Example screenshot:
<img width="1180" alt="Image 2020-06-07 at 10 11 47 PM" src="https://user-images.githubusercontent.com/7323966/83979063-e92d0e80-a90b-11ea-99e1-1fa823e00b4e.png">

**Comment by dannyvankooten** [comment]
Hey @jeroenrotty,

I love this idea but I think the featured  image and styling is actually not default WordPress behavior. Are you sure that isn't handled by your theme or a plugin?

**Comment by jeroenrotty** [comment]
Good question @dannyvankooten, let me check and verify 🙈.

**Comment by jeroenrotty** [comment]
Hmm, okay. Widget has almost the same name than the default one. It's my theme that has this output on that specific widget. For reference (if you'd like to integrate it, I'm using [Chaplin](https://andersnoren.se/themes/chaplin/)).

**Comment by dannyvankooten** [comment]
Thanks for checking, I thought so. I'm afraid spending time on this isn't really worth it for me because of it being a specific theme but if you really want this then I recommend looking at the `KokoAnalytics\get_most_viewed_posts` function ([here](https://github.com/ibericode/koko-analytics/blob/9504b4dff8bcca8e8d2558b5078ff60df4f64b2b/src/functions.php#L99)).

These are the relevant classes in the plugin:

- [src/class-widget.php](https://github.com/ibericode/koko-analytics/blob/master/src/class-widget-most-viewed-posts.php)
- [src/class-shortcode.php](https://github.com/ibericode/koko-analytics/blob/master/src/class-shortcode-most-viewed-posts.php)

Or in code:

```php
<?php
$default_args = array(
  'number'    => 5,
  'post_type' => 'post',
  'show_date' => false,
  'days'    => 30,
);
$posts = KokoAnalytics\get_most_viewed_posts( $args );

$html = '<ul>';
foreach ( $posts as $p ) {
  $post_title   = get_the_title( $p );
  $title        = $post_title !== '' ? $post_title : esc_html__( '(no title)', 'koko-analytics' );
  $aria_current = '';

  if ( get_queried_object_id() === $p->ID ) {
	$aria_current = ' aria-current="page"';
  }

  $html .= '<li>';
  $html .= sprintf( '<a href="%s" %s>%s</a>', get_the_permalink( $p ), $aria_current, $title );

  if ( $args['show_date'] ) {
	$html .= sprintf( PHP_EOL . ' <span class="post-date">%s</span>', get_the_date( '', $p ) );
  }
  $html .= '</li>';
}
$html .= '</ul>';
echo $html;
```

**Comment by jeroenrotty** [comment]
Thank you for guiding me in the code of Koko, I'll check it out and see if I find it worthwhile as well. Thanks Danny.
