### ISSUE TITLE
Request - public facing stats

### ISSUE THREAD

**Issue by dddddddavid** [ibericode/koko-analytics#80]
Hi Danny,

It would be really cool to be able to show the site stats as a public facing wordpress page. Basically, what I see in the admin view, with graphs, refererers and top articles etc, but so everyone can see.

Is this possible?

David

edit: I've just seen that your demo site gives only access to the analytics page and doesn't require a login. If 'settings' was disabled, that would be perfect for me.

**Comment by dannyvankooten** [comment]
Hey @dddddddavid,

The "settings" tab showing on kokoanalytics.com is actually a tiny bug, hah. Changing any of the settings won't actually work because the demo user lacks the required capability. So that looks like it does what you want it to do.

To get that working you need to set-up a user with the `view_koko_analytics` capability. That will give that user role access to the Koko Analytics dashboard but not allow it to change any of its settings. 

For the demo website I've created a single user of the `subscriber` role and granted it the necessary capability using the [User Role Editor](https://wordpress.org/plugins/user-role-editor/) plugin. I then added in a link that automatically logs in that user whenever that link is clicked.

Does that help? If not, just let me know.

**Comment by dddddddavid** [comment]
Nice - it does help.

How do you set up the link for passwordless login? I can't even create a user without specifying a password.
