### ISSUE TITLE
Feature Suggestion: Sample Privacy Policy Guide

### ISSUE THREAD

**Issue by kamauwanjoroge** [ibericode/koko-analytics#82]
Hi @dannyvankooten. This is just a personal suggestion but which I find worthwhile. I was trying to look for a way to include Koko analytics in my privacy policy but I could not find a way to express it in words e.g. what it does, what data it collects, etc. Is it possible for you to generate a sample privacy policy guide that can appear in the Privacy section of WP-Admin?

**Comment by danielrunvegan** [comment]
I like that idea, too! I have written the following passage on Koko Analytics in my own privacy policy. You can copy it if you like (at your own risk of course), and Danny can use it as a starting point if he chooses to implement this feature:

"We use the WordPress plugin Koko Analytics on our website to measure key figures that are important to us, such as the number of visitors and page views.

We have configured Koko Analytics so that this measurement is carried out absolutely anonymously. Neither cookies are set nor any personal data collected.

If you still do not want your visit to our website to be included in the measurement, you can activate the "Do Not Track" function of your browser, which is respected by Koko Analytics."

**Comment by askel45** [comment]
@danielrunvegan thanks! I use cookies for mine, but I worded it in a similar way. With more features in the pipeline, this idea becomes inevitable.

**Comment by dannyvankooten** [comment]
👍 Love the idea, I'll take a stab at it.

**Comment by askel45** [comment]
> 👍 Love the idea, I'll take a stab at it.

Great!

**Comment by albertvisuals** [comment]
+1

**Comment by dannyvankooten** [comment]
Moved to #214
