### ISSUE TITLE
Determine if user has consented to cookies

### ISSUE THREAD

**Issue by jayhybrid** [ibericode/koko-analytics#91]
Hey,

I am a novice programmer and I'm trying to learn by making my own cookie consent plugin in WP. I read that I can use 
```
window.koko_analytics.use_cookie
```
to get the consent of a user but in my tests this variable reloads after each page refresh. I tried looking up a list of koko hooks, filters, actions but I can't find anything.

How can I determine if the user has already consented so I can only prompt the user if he hasn't consented?

**Comment by dannyvankooten** [comment]
Hello @jayhybrid,

The `window.koko_analytics.use_cookie` is only for instructing the plugin whether to place a cookie or not, it does not actually track or manage consent from the user. This is up to you or your cookie consent plugin.

Lots of cookie consent plugins allow outputting a snippet of JavaScript **only after the user has consented** so that's where you would usually place a snippet like this to instruct Koko Analytics that it is okay to set a cookie:

```js
window.koko_analytics.use_cookie = true;
```

In the default scenario the `window.koko_analytics.use_cookie` will simply reflect the value from your  **Koko Analytics > Settings** page.

I hope that helps. Good luck!

**Comment by grandeljay** [comment]
Hey, thanks for the help so far.

I am using `window.koko_analytics.use_cookie = false;` in the event of a user revoking his consent again. The cookie seems to remain. Shouldn't it be deleted?

**Comment by dannyvankooten** [comment]
Hey @grandeljay,

Currently Koko does not include any logic to delete the cookie again, but if `use_cookie === false` then the cookie will not be read anyway. The cookie expires 6 hours after it was set, so it should automatically be removed.
